name: demo
on:
  push:
    branches: [ biswajit-1 ]
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Setting up JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: 11
            distribution: 'adopt'
        - name: Making gradlew executable
          run: chmod +x ./gradlew
        - name: Building with Gradle
          run: ./gradlew build
        - name: Unit Test
          run: ./gradlew test
        - name: Test Report Generator
          uses: asadmansr/android-test-report-action@v1.2.0
          if: ${{ always() }}
          with:
            files: test-results/**/*.xml