name: Building Image
on:
  push:
    branches: [ biswajit-1 ]
jobs:
  build-and-push-image-to-github-container-registry:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Image
        run: docker build - < Dockerfile -t ghcr.io/biswajit-1/myimage:1.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITPACK_IMAGE_TOKEN }}

      - name: Pushing to GitHub Container Registry
        run: |
           docker push ghcr.io/digitalinnovation/myimage:1.0