name: Building Image
on:
  push:
    branches: [ biswajit-1 ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          login-server: leaptest1.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

          - run: |
              run: docker build -< Dockerfile -t ghcr.io/biswajit-roy76/myimage:1.0
              docker push docker pus/appdb:${{ github.sha }}/appdb:${{ github.sha }}
