name: Building Image
on:
  push:
    branches: [ biswajit-1 ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          run: docker build -< Dockerfile -t leaptest1.azurecr.io/biswajit-roy76/myimage:1.0
          docker push/appdb:${{ github.sha }}/appdb:${{ github.sha }}

      - name: Docker Login
      - uses: azure/docker-login@v1
        with:
          login-server: leaptest1.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

