name: CI

on: [ push ]

jobs:
  image-build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:18.04
    steps:
      - name: Building Docker Image
        run: docker build -t myimage:1.0 ./Dockerfile
